update anthony sesuai todo
wicaksonoe/pdm-rfid pull request #4
Opened 2020-10-23 18:07 UTC by Mbahmo

update anthony sesuai todo

2020-10-24 04:26 UTC, wicaksonoe requested changes
ton. di edit di file request nya lagi dikit yaa. h3h3

2020-10-24 04:26 UTC, wicaksonoe commented on app/Http/Requests/DosenRequest.php
> +                        // Rule::unique('mdosen')->ignore($this->nidn, 'nidn'),
Rule unique di method PUT/PATCH juga jangan lupa. kalo ga di protect takutnya pas ngedit bisa ada 2 nidn yang sama.

2020-10-24 04:26 UTC, wicaksonoe commented on app/Http/Requests/DosenRequest.php
> +            'nidn.required'         => 'nidn tidak boleh kosong.',
message NIDN unique juga

2020-10-24 17:52 UTC, Mbahmo commented
udah @wicaksonoe

2020-10-26 02:29 UTC, wicaksonoe approved these changes

2020-10-26 02:31 UTC, merged